name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to production
        run: |
          # Add your deployment commands here
          # Example: deploy to a server using SSH or push to a cloud platform

      - name: Cleanup
        run: npm run cleanup
